# Generated by Django 2.2.15 on 2021-06-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='Users/%Y/%m/%d')),
                ('address', models.CharField(max_length=70)),
            ],
        ),
    ]
