# Generated by Django 2.2.15 on 2021-06-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
